### ISSUE TITLE
Image data link seems not active

### ISSUE THREAD

**Issue by hliu-opt-5143** [YuchenLou/ZO-BCD#1]
Hi.

Nice work and nice paper!

I was trying to download the data set for the image case. However, the link seems not active. Would you please help check? Thanks

**Comment by YuchenLou** [comment]
Hi,

Thank you for pointing out the issue! Now the old link is replaced, and the new link is referred to the official website of ImageNet for downloading the dataset (which should be more robust to changes). 

As a remark, the codes should work for any image from the ImageNet dataset from any sources (or even images from other dataset. Here we simply apply the model inception-v3 which is already trained on the ImageNet), so feel free to use your own available sources for the test. The only thing that probably needs to be changed when using other sources is the format of the name of the images, or the reading process of the names. In our codes we assume a format of the name to be "x.y.jpg", where x is for the index of the correct label. You can modify this in "ZOBCD_Image_Attack.m" Line 72-74 for other name formats.

Let us know if there is any other problem. Thanks!

**Comment by hliu-opt-5143** [comment]
Thank you! The paper says you tested on 1000 image randomly selected from ImageNet. I was therefore hoping to perform tests on those 1000 images, if at all possible... Thanks!
