### ISSUE TITLE
"Index exceeds the number of array elements." Error

### ISSUE THREAD

**Issue by hql5143** [YuchenLou/ZO-BCD#2]
Hi,

I tried to run the codes for the audio case. The code would repetitively produce an error as below:

"Index exceeds the number of array elements. Index must not exceed <...>.

"Error in ZOBCD_Audio_Targeted_Attack (line 54)
        ii = Order_of_Attack(i);
 

Would you please advise? Thank you for your help!

**Comment by YuchenLou** [comment]
Hi,

Thanks for pointing out the issue! I have tried the codes but there seems to be no problem on my side. So there should be no problem on the algorithm, but on the process of reading the files. Some suggestions I can offer for you to check: 

1. The error you mention may appear if your folder contains fewer sound files which are **correctly classified** by the NN than the required attack number (which is the variable "num_attack", by default set as 50). Note that we only do the attack if the sound is correctly labelled by the NN (this process is starting from line 59), not all the files. So check the number of correct files in your folder.
2. Check if you get the info of the correct label correctly. Note now in line 62&63 we get the true lable by identifying the name of the folders. If you use different names (i.e., the folder name is not the corresponding label name), or your path is not separated by "/" but "``\``", or some other possible reasons, you don't get the true label, and in this case you can not get any correctly classified audio, which also gives you the issue.

Hope it helps.
