### ISSUE TITLE
Which version of MATLAB are you using for coding

### ISSUE THREAD

**Issue by FL-sky** [YuchenLou/ZO-BCD#3]

**Comment by YuchenLou** [comment]
It was done in 2019b, and any version later than that shall work (We have tested on 2020 & 2021). Note that some toolboxes require at least 2019b.

**Comment by FL-sky** [comment]
Thank you for letting me know that it's not related to the version of MATLAB. I add "openExample('deeplearning_shared/DeepLearningSpeechRecognitionExample')" to the first line in audio attack.

# I don't know the definition  of the SNR. Is this  correct?
########
import scipy.io.wavfile as wav
_, ori = wav.read('ori.wav')
_, adv = wav.read('adv.wav')
energy_a = np.sum(ori ** 2)
noise_signal = adv - ori
energy_noise = np.sum(noise_signal ** 2)
SNR_dB = 10 * np.log10(energy_a / energy_noise)

##########
#and  dbx, is this right?

dbx = 20 * np.log10(np.max(np.abs(adv-ori)))-20 * np.log10(np.max(np.abs(ori)))

**Comment by YuchenLou** [comment]
I am very sorry for the late update! Something came up and I forgot to follow up your question. 

I don't quite understand your question on "SNR". The following codes are, I guess, your Python implementation for the audio adversarial attack? I believe we did not write these lines of codes in our matlab version for audio attack. Would you specify what do you mean by this?

I guess your "dbx" is the objective function from Carlini & Wagner. This looks correct to me.

**Comment by FL-sky** [comment]
it doesnt matter.

In your paper, there is indeed no code related to signal-to-noise ratio. I have seen this indicator (SNR) while reading some papers about audio adversarial example, but they didnt provide the calculation process.

thanks

**Comment by YuchenLou** [comment]
Thanks for the clarification! I will close this issue if there is no further question. Please feel free to contact me via email or opening another issue if there is any further question.
